# Introduction 

## Explanation & Prediction

For any particular analysis conducted, emphasis can be placed on understanding the underlying mechanisms that have specific theoretical underpinnings, versus a focus that dwells more on performance and, more to the point, future performance.  These are not mutually exclusive goals in the least, and probably most studies contain a little of both in some form or fashion.  I will refer to the former emphasis as that of *explanation*, and the latter that of *prediction*[^infpred].

In studies with a more explanatory focus, traditional analysis concerns a single data set.  For example, one assumes a data generating distribution for the response (e.g. Gaussian, poisson), and then evaluates the overall fit of a single model to the data at hand, e.g. in terms of R-squared, and statistical significance for the various features in the model.  After that, one assesses how well the model lines up with the theory that led to the analysis, and modifies it accordingly if need be, for future studies to consider.  Some studies might look at predictions for specific, possibly hypothetical values of the features, or examine the particular nature of their effects.  In many cases, only a single model is considered.  In these settings, little attempt is made to explicitly understand how well the model will do with data it hasn't seen, but we hope to have gained greater insight as to the underlying mechanisms guiding the target variable of interest.  Following @breiman_statistical_2001, this would be more akin to the *data modeling culture*.

For studies focused on prediction, other techniques are available that are far more focused on performance, not only for the current data under examination, but for future data the selected model might be applied to.  While still possible, relative feature importance is often less of an issue, and oftentimes there may be no particular theory to drive the analysis.  There may be thousands of input variables and countless parameters to estimate, such that no simple summary would likely be possible anyway.  However, many of the techniques applied in these analyses are quite powerful, and steps are taken to ensure better results for new data.  Referencing Breiman again, this perspective is more of the *algorithmic modeling culture*.

While the two approaches are not exclusive, I present two extreme (though thankfully dated) views of the situation[^kerby]:

>To paraphrase provocatively, 'machine learning is statistics minus any checking of models and assumptions'.
<br> $\sim$ Brian Ripley, 2004


... the focus in the statistical community on data models has:

>
- Led to irrelevant theory and questionable scientific conclusions.
- Kept statisticians from using more suitable algorithmic models.
- Prevented statisticians from working on exciting new problems.
<br>
$\sim$ Leo Breiman, 2001


Respective departments of computer science, statistics, and related fields, now overlap more than ever, as more relaxed views prevail today. However, there are potential drawbacks to placing too much emphasis on explanation or prediction.  Performant models that 'just work' have the potential to be dangerous or used unethically if they are little understood.  Conversely, situations where a lot of time is spent sorting out details for an ill-fitting model suffers its own problem-  a variable amount of understanding coupled with little pragmatism.  While this document will focus on more prediction-focused approaches, guidance will be provided with an eye toward their use in situations where the typical explanatory approach would be applied, hopefully shedding some light on a path toward obtaining the best of both worlds.

## Terminology

For those used to statistical concepts such as dependent variables, clustering, and predictors, etc. you will have to get used to some differences in terminology such as targets, unsupervised learning, and features etc.  It doesn't take too much to get acclimated, even if it is somewhat annoying when one is first starting out[^mlgloss].  I won't be too beholden to either in this paper, and it should be clear from the context what's being referred to.  Initially I will start off mostly with non-ML terms and note in brackets an ML version to help the orientation along.

## Supervised vs. Unsupervised

At least one distinction should be made from the outset, *supervised* vs. *unsupervised* learning.  Supervised learning is the typical regression or classification situation where we are trying to predict some target variable of interest, possibly several. Unsupervised learning seeks patterns within the data without regard to any specific target variable, and would include things like cluster analysis, principal components analysis, autoencoders, etc. They can also be used in conjunction, and in some settings the distinction is blurry. The focus of this document will be almost entirely on supervised learning, though we will discuss some forms of unsupervised learning by the end.


## Tools You Can Start With

One thing that is important to keep in mind as you begin is that standard techniques from traditional statistics are still available in ML, although even then we might tweak them or do more with them.  So having a basic background in regression, which you'd have with basic statistical training, is all that is required to get started with machine learning.  Again, the difference between ML and traditional statistical analysis is more of focus than method.



### The Standard Linear Model

All introductory statistics courses will cover linear regression in great detail, and it can certainly serve as a starting point here.  We can describe it as follows in matrix notation in terms of the underlying data generating process:

$$\mu = X\beta$$
$$y \sim N(\mu,\sigma^{2}\textrm{I})$$

Where $y$ is conditionally  a normally distributed response [*target*] with mean $\mu$ and constant variance $\sigma^{2}$.  X is a typical model matrix, i.e. a matrix of variables and in which the first column is typically a vector of 1s for the intercept [*bias*][^bias], and $\beta$ is the vector of coefficients [*weights*] corresponding to the intercept and features in the model matrix.

What might be given less focus in applied courses is how often standard regression won't be the best tool for the job, or even applicable in the form it is usually presented.  Because of this, many are still hammering screws with it, even as the explosion of statistical techniques of the past quarter century or more has rendered obsolete many current introductory statistical texts that are written for specific disciplines.  Even so, the concepts you can gain in learning the standard linear model are generalizable, and even a few modifications of it, while still maintaining the basic design, can render it still very effective in situations where it is appropriate.

Typically, in fitting [*training*] a model we tend to talk about R-squared and statistical significance of the coefficients for a small number of features.  For our purposes, let's instead switch the focus to be on the residual sum of squares[^sos], or *error*, with an eye towards minimizing it, and model comparison using it. In ML, we won't have a situation where we are only considering one model fit, and so we have to find one that reduces the sum (or mean) of the squared errors, which amounts to reducing our prediction error, but without *overfitting*, a concept we'll return to later.  Furthermore, we will be much more concerned with how the model performs on new data that we haven't seen yet [*generalization*].



### Logistic Regression

Logistic regression is often used where the response is categorical in nature, usually with binary outcome in which some event occurs or does not occur [*label*].  One could still use the standard linear model here, but you could end up with nonsensical predictions, to go along with other shortcomings.  Furthermore, it's no more effort, nor is any understanding lost, in using a logistic regression over the linear probability model.  It's also good to keep logistic regression in mind as we discuss other classification approaches later on.

Logistic regression is also typically covered in an introduction to statistics for applied disciplines because of the pervasiveness of binary responses, or responses that have been made as such[^discretize].  Like the standard linear model for a continuous target, just a few modifications can enable you to use it to provide better performance, particularly with new data.  The take home message at this point is that we don't have to abandon familiar tools in the move toward a machine learning perspective.


### Expansions of Those Tools

#### Generalized Linear Models 

Logistic regression is a *generalized linear model *assuming a binomial/bernoulli distribution for the response and with a *logit* link function as follows:


$$\eta = X\beta$$
$$\eta = g(\mu)$$
$$\mu = g(\eta)^{-1}$$
$$y \sim \mathrm{Bin}(\mu, \mathrm{size}=1)$$

This is the same presentation format as seen with the standard linear model presented before, except now we have a link function $g(.)$ and so are dealing with a transformed response.  In the case of the standard linear regression model, the distribution assumed is the Gaussian (normal) and the link function is the identity link, i.e. no transformation is made. The link function used will depend on the analysis performed, and while there is choice in the matter, the GLM distributions used have a typical, or canonical link function[^poisson].

Generalized linear models expand the standard linear model beyond the Gaussian/normal distribution for the response, and allow for better fitting models of categorical, count, and skewed response variables.  We also have a counterpart to the residual sum of squares, though we'll now refer to it as the *deviance*.


#### Generalized Additive Models

Additive models extend the generalized linear model to incorporate nonlinear relationships of features to the response. We might note it as follows:


$$\eta = X\beta + f(Z)$$
$$\mu = g(\eta)^{-1}$$
$$y \sim \mathrm{family}(\mu, ...)$$


So we have the generalized linear model, but also smooth functions $f(Z)$ of one or more features.  More detail can be found in @wood_generalized_2006 and I provide an introduction [here](https://m-clark.github.io/generalized-additive-models/).  

Things do start to get fuzzy with GAMs.  It becomes more difficult to obtain statistical inference for the smooth terms in the model, and the nonlinearity does not always lend itself to easy interpretation.  However, really this just means that we have a little more work to get the desired level of understanding.  GAMs can be seen as a segue toward more black box/algorithmic techniques we'll see later.  Compared to some of those techniques in machine learning, GAMs are notably more interpretable, though GAMs are perhaps less so than GLMs.  Also, part of the estimation process includes regularization and validation in determining the nature of the smooth function, topics of which we will return later.

So at this point, if you have a basic idea of a linear model, whether used for a numeric or binary outcome, you're well on the way to your machine learning adventure!  Understanding these tools give you all you need to to start using ML, but there are some additional concepts we'll also want to pick up on first to really hit the ground running.

[^mlgloss]: See  [the Google Machine Learning Glossary](https://developers.google.com/machine-learning/glossary) for reference.

[^kerby]: A favorite saying I heard while working at the University of Michigan is 'Machine learning is magic!', attributed to CSCAR director Kerby Shedden, in response to a client's over enthusiasm to something they did not understand well.  As [Arthur C. Clarke put it](https://en.wikipedia.org/wiki/Clarke's_three_laws): 'Any sufficiently advanced technology is indistinguishable from magic.', and the same idea can be applied to modeling techniques.

[^bias]: Yes, you will see 'bias' refer to an intercept, and also mean something entirely different in our discussion of bias vs. variance.  Often, techniques inherently induce bias to get better prediction (see the [regularization][Regularization] section).

[^sos]: $\sum(y-f(x))^{2}$ where $f(x)$ is a function of the model features, and in this context a linear combination of them ($X\beta$).

[^discretize]: It is generally a bad idea to discretize continuous variables, especially the dependent variable. However contextual issues, e.g. disease diagnosis, might warrant it.

[^poisson]: As another example, for the Poisson distribution, the typical link function would be the $log(\mu)$.

[^infpred]: In other words, there are cases where we are more interested in statistical inference and hypothesis testing versus times where we are more in performance.