# Preface


## Overview

The purpose of this document is to provide a conceptual introduction to statistical or machine learning (ML) techniques for those just starting out. *Machine learning*[^mlothername] can be described as a form of data analysis, often even utilizing well-known and familiar techniques, that has bit of a different focus than traditional statistical practice.  The key notion is that flexible, automatic approaches are used to detect patterns within the data, with a primary focus on making predictions on future data.

If one surveys the number of techniques available in ML without any context, one can easily be overwhelmed by the sheer number of approaches, as well as the various tweaks and variations of them.  However, the specifics of the techniques are not as important as more general concepts that would be applicable in most every ML setting, and many traditional statistical techniques as well.  While there will be examples using the R language and descriptions of a few specific approaches, the focus here is more on ideas than application and kept at the conceptual level as much as possible.  In addition, the orientation here is for so-called *tabular data* settings, not natural language or computer vision, but again, the concepts would generalize to most. Note that Python versions of the model examples are available [here](https://github.com/m-clark/introduction-to-machine-learning/blob/master/black_box.ipynb).  


## Prerquisites

As for prerequisite knowledge, I will assume a basic familiarity with basic regression analysis.  Regarding programming, none is really required to follow most of the content here, but some knowledge of R would be helpful if one wants to do the examples.  Note that I won't do much explaining of the code, as I will be more concerned with getting to a result than clearly detailing the path to it.  Armed with even introductory knowledge, if there are parts of R code that are unclear, there are many resources to investigate and discover the details on one's own, which results in more learning anyway.


## Additional Details

The latest version of this document is dated `r Sys.Date()`.  It was originally written in March 2013, when there was much more need for it in academia where I was employed, at least outside of CS and Engineering departments.  For all the buzz of machine learning, deep learning, AI, etc., that need still exists I think, as applied disciplines are only now starting to teach techniques as a core part of their training, many still aren't, and even many in industry do not take advantage of a data-driven approach.  However, the number of tools and information, within the realm of R and Python especially, is vast, so you'll have plenty to keep you occupied.  Indeed, I'm not sure how much of the specific techniques and tools demonstrated in this document will even be viable in another couple years, so be prepared to keep up. I should also note that I was originally trained in traditional statistics, and the perspective here is colored, but not determined, by that.  This document should be particularly useful for those coming from a background in applied statistical analysis.


Color coding in text:

- *emphasis*
- <span class="pack">package</span>
- <span class="func">function</span>
- <span class="objclass">object/class</span>
- [link]()


For those interested, I post regularly on machine learning and related topics at my [website](https://m-clark.github.io/), and [here is more about my background](https://m-clark.github.io/about.html).


[^mlothername]: Also referred to as statistical learning, statistical engineering, data science or data mining in various academic, professional, and other contexts (correctly or not).

[^moredata]: Indeed, there is evidence that with large enough samples many techniques converge to similar performance.